### ISSUE TITLE
minIndicNSFWDetector -- not able to detect all the variations of abusive words

### ISSUE THREAD

**Issue by lalitkishorevyas** [swapniljadhav1921/asamiasami#1]
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from asamiasami import minIndicNSFWDetector
>>> model = minIndicNSFWDetector(run_option="cpu")
>>> model.getNSFWClass("Text for which safe unsafe to be detected")
{'sfw': 1.0, 'nsfw': 0.0}
>>> model.getNSFWClass("madarchod ke bacche")
{'sfw': 0.0, 'nsfw': 1.0}
>>> model.getNSFWClass("hot chat karoge")
{'sfw': 1.0, 'nsfw': 0.0}
>>> model.getNSFWClass("hot chat")
{'sfw': 1.0, 'nsfw': 0.0}
>>> model.getNSFWClass("hot chat karlo sexy")
{'sfw': 0.0, 'nsfw': 1.0}
>>> model.getNSFWClass("hot chat karlo sex")
{'sfw': 0.0, 'nsfw': 1.0}
>>> model.getNSFWClass("hot chat karlo se")
{'sfw': 1.0, 'nsfw': 0.0}
>>> model.getNSFWClass("tum  s e x karogay mere sath")
{'sfw': 1.0, 'nsfw': 0.0}
>>> model.getNSFWClass("burchod")
{'sfw': 0.0, 'nsfw': 1.0}
>>> model.getNSFWClass("bur chod")
{'sfw': 0.0, 'nsfw': 1.0}
>>> model.getNSFWClass("bur")
{'sfw': 1.0, 'nsfw': 0.0}
>>> model.getNSFWClass("gand faad di")
{'sfw': 0.0, 'nsfw': 1.0}
>>> model.getNSFWClass("21hub")
{'sfw': 1.0, 'nsfw': 0.0}
>>> model.getNSFWClass("247bigboobs")
{'sfw': 1.0, 'nsfw': 0.0}
>>> model.getNSFWClass("ass fucker")
{'sfw': 0.0, 'nsfw': 1.0}

**Comment by swapniljadhav1921** [comment]
NSFW is very difficult to define. In some Indian languages saying sala, dog has not much insult ... but in some languages, they are considered as insults. So better fine-tune the model with your own data. In my data, sex, hot chat are not defined as NSFW.

Apart from that, I have added a nsfw phrase file [here](https://github.com/swapniljadhav1921/asamiasami/blob/main/minIndicNSFWDetector/NSFWFinal.txt)
You can add remove according to your use case. Also, you can have simple rule system either to consider model probability or number of hard/soft match found.

Hard Match => Full word, phrase match
Soft Match => Partial word, phrase match

```
>>> from asamiasami import minIndicNSFWDetector
>>> model = minIndicNSFWDetector()
>>>
>>> model.getNSFWClass("pagal sale gandu he kya")
{'hard_match': ['gandu'], 'soft_match': ['gandu', 'gand'], 'model_output': {'sfw': 0.0, 'nsfw': 1.0}}
>>>
>>> model.getNSFWClass("tum s e x karogay mere sath")
{'hard_match': ['sex'], 'soft_match': ['gay', 'sex'], 'model_output': {'sfw': 1.0, 'nsfw': 0.0}}
>>>
```

**Comment by lalitkishorevyas** [comment]
@swapniljadhav1921 thank you sirji

**Comment by swapniljadhav1921** [comment]
Closing the issue as no further questions are followed.
