### ISSUE TITLE
unable to  download files from git-lfs

### ISSUE THREAD

**Issue by akshay951228** [swapniljadhav1921/asamiasami#4]
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.                                            
error: failed to fetch some objects from 'https://github.com/swapniljadhav1921/asamiasami.git/info/lfs'

**Comment by swapniljadhav1921** [comment]
Addressing issue here -> https://github.com/swapniljadhav1921/asamiasami/issues/2
And closing this one.
